//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.17 at 04:43:59 PM CET 
//


package com.adoulfakkar.quizzApp.service.wsdl.auth;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for isValidCert complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="isValidCert">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="cert" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="testDate" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="testRevoked" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "isValidCert", propOrder = {
    "id",
    "cert",
    "testDate",
    "testRevoked"
})
public class IsValidCert {

    protected String id;
    protected byte[] cert;
    protected boolean testDate;
    protected boolean testRevoked;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the cert property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getCert() {
        return cert;
    }

    /**
     * Sets the value of the cert property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setCert(byte[] value) {
        this.cert = ((byte[]) value);
    }

    /**
     * Gets the value of the testDate property.
     * 
     */
    public boolean isTestDate() {
        return testDate;
    }

    /**
     * Sets the value of the testDate property.
     * 
     */
    public void setTestDate(boolean value) {
        this.testDate = value;
    }

    /**
     * Gets the value of the testRevoked property.
     * 
     */
    public boolean isTestRevoked() {
        return testRevoked;
    }

    /**
     * Sets the value of the testRevoked property.
     * 
     */
    public void setTestRevoked(boolean value) {
        this.testRevoked = value;
    }

}
