//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.17 at 04:43:59 PM CET 
//


package com.adoulfakkar.quizzApp.service.wsdl.auth;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.adoulfakkar.quizzApp.service.wsdl.auth package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SetPassword_QNAME = new QName("http://ws.ldap.quizzApp.com/", "setPassword");
    private final static QName _GetDynamics_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getDynamics");
    private final static QName _IsAlive_QNAME = new QName("http://ws.ldap.quizzApp.com/", "isAlive");
    private final static QName _Login_QNAME = new QName("http://ws.ldap.quizzApp.com/", "login");
    private final static QName _GetNewPassword_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getNewPassword");
    private final static QName _LdapWsException_QNAME = new QName("http://ws.ldap.quizzApp.com/", "LdapWsException");
    private final static QName _LoginCryptResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "loginCryptResponse");
    private final static QName _SetCaptchaAsPassword_QNAME = new QName("http://ws.ldap.quizzApp.com/", "setCaptchaAsPassword");
    private final static QName _GetCertStringAttribut_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getCertStringAttribut");
    private final static QName _LoginCrypt_QNAME = new QName("http://ws.ldap.quizzApp.com/", "loginCrypt");
    private final static QName _SetCaptchaAsPasswordResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "setCaptchaAsPasswordResponse");
    private final static QName _GetSitesResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getSitesResponse");
    private final static QName _GetProfilResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getProfilResponse");
    private final static QName _GetCert_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getCert");
    private final static QName _GetPrivilegesResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getPrivilegesResponse");
    private final static QName _IsNotRevokedCertResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "isNotRevokedCertResponse");
    private final static QName _GetCertByteAttribut_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getCertByteAttribut");
    private final static QName _GetProfil_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getProfil");
    private final static QName _GetAttribut_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getAttribut");
    private final static QName _GetAttributResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getAttributResponse");
    private final static QName _GetCaptcha_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getCaptcha");
    private final static QName _LoginCertResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "loginCertResponse");
    private final static QName _SetPasswordCert_QNAME = new QName("http://ws.ldap.quizzApp.com/", "setPasswordCert");
    private final static QName _GetCertResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getCertResponse");
    private final static QName _GetCaptchaResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getCaptchaResponse");
    private final static QName _GetCertStringAttributResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getCertStringAttributResponse");
    private final static QName _SetPasswordResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "setPasswordResponse");
    private final static QName _GetRolesResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getRolesResponse");
    private final static QName _GetNewPasswordResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getNewPasswordResponse");
    private final static QName _IsNotRevokedCert_QNAME = new QName("http://ws.ldap.quizzApp.com/", "isNotRevokedCert");
    private final static QName _LoginCert_QNAME = new QName("http://ws.ldap.quizzApp.com/", "loginCert");
    private final static QName _GetPrivileges_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getPrivileges");
    private final static QName _GetRoles_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getRoles");
    private final static QName _GetCertByteAttributResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getCertByteAttributResponse");
    private final static QName _IsValidCert_QNAME = new QName("http://ws.ldap.quizzApp.com/", "isValidCert");
    private final static QName _SetPasswordCertResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "setPasswordCertResponse");
    private final static QName _GetDynamicsResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getDynamicsResponse");
    private final static QName _IsValidCertResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "isValidCertResponse");
    private final static QName _LoginResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "loginResponse");
    private final static QName _GetSites_QNAME = new QName("http://ws.ldap.quizzApp.com/", "getSites");
    private final static QName _IsAliveResponse_QNAME = new QName("http://ws.ldap.quizzApp.com/", "isAliveResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.adoulfakkar.quizzApp.service.wsdl.auth
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link LoginCryptResponse }
     * 
     */
    public LoginCryptResponse createLoginCryptResponse() {
        return new LoginCryptResponse();
    }

    /**
     * Create an instance of {@link IsNotRevokedCert }
     * 
     */
    public IsNotRevokedCert createIsNotRevokedCert() {
        return new IsNotRevokedCert();
    }

    /**
     * Create an instance of {@link GetCertStringAttribut }
     * 
     */
    public GetCertStringAttribut createGetCertStringAttribut() {
        return new GetCertStringAttribut();
    }

    /**
     * Create an instance of {@link GetSites }
     * 
     */
    public GetSites createGetSites() {
        return new GetSites();
    }

    /**
     * Create an instance of {@link GetCaptchaResponse }
     * 
     */
    public GetCaptchaResponse createGetCaptchaResponse() {
        return new GetCaptchaResponse();
    }

    /**
     * Create an instance of {@link LoginCrypt }
     * 
     */
    public LoginCrypt createLoginCrypt() {
        return new LoginCrypt();
    }

    /**
     * Create an instance of {@link GetProfil }
     * 
     */
    public GetProfil createGetProfil() {
        return new GetProfil();
    }

    /**
     * Create an instance of {@link GetPrivilegesResponse }
     * 
     */
    public GetPrivilegesResponse createGetPrivilegesResponse() {
        return new GetPrivilegesResponse();
    }

    /**
     * Create an instance of {@link LoginResponse }
     * 
     */
    public LoginResponse createLoginResponse() {
        return new LoginResponse();
    }

    /**
     * Create an instance of {@link GetCertStringAttributResponse }
     * 
     */
    public GetCertStringAttributResponse createGetCertStringAttributResponse() {
        return new GetCertStringAttributResponse();
    }

    /**
     * Create an instance of {@link GetCertByteAttributResponse }
     * 
     */
    public GetCertByteAttributResponse createGetCertByteAttributResponse() {
        return new GetCertByteAttributResponse();
    }

    /**
     * Create an instance of {@link SetPassword }
     * 
     */
    public SetPassword createSetPassword() {
        return new SetPassword();
    }

    /**
     * Create an instance of {@link IsAliveResponse }
     * 
     */
    public IsAliveResponse createIsAliveResponse() {
        return new IsAliveResponse();
    }

    /**
     * Create an instance of {@link LdapWsException }
     * 
     */
    public LdapWsException createLdapWsException() {
        return new LdapWsException();
    }

    /**
     * Create an instance of {@link GetCertResponse }
     * 
     */
    public GetCertResponse createGetCertResponse() {
        return new GetCertResponse();
    }

    /**
     * Create an instance of {@link GetDynamics }
     * 
     */
    public GetDynamics createGetDynamics() {
        return new GetDynamics();
    }

    /**
     * Create an instance of {@link IsValidCert }
     * 
     */
    public IsValidCert createIsValidCert() {
        return new IsValidCert();
    }

    /**
     * Create an instance of {@link GetCertByteAttribut }
     * 
     */
    public GetCertByteAttribut createGetCertByteAttribut() {
        return new GetCertByteAttribut();
    }

    /**
     * Create an instance of {@link GetProfilResponse }
     * 
     */
    public GetProfilResponse createGetProfilResponse() {
        return new GetProfilResponse();
    }

    /**
     * Create an instance of {@link GetRolesResponse }
     * 
     */
    public GetRolesResponse createGetRolesResponse() {
        return new GetRolesResponse();
    }

    /**
     * Create an instance of {@link SetPasswordResponse }
     * 
     */
    public SetPasswordResponse createSetPasswordResponse() {
        return new SetPasswordResponse();
    }

    /**
     * Create an instance of {@link GetCaptcha }
     * 
     */
    public GetCaptcha createGetCaptcha() {
        return new GetCaptcha();
    }

    /**
     * Create an instance of {@link IsAlive }
     * 
     */
    public IsAlive createIsAlive() {
        return new IsAlive();
    }

    /**
     * Create an instance of {@link SetPasswordCertResponse }
     * 
     */
    public SetPasswordCertResponse createSetPasswordCertResponse() {
        return new SetPasswordCertResponse();
    }

    /**
     * Create an instance of {@link Login }
     * 
     */
    public Login createLogin() {
        return new Login();
    }

    /**
     * Create an instance of {@link GetAttribut }
     * 
     */
    public GetAttribut createGetAttribut() {
        return new GetAttribut();
    }

    /**
     * Create an instance of {@link SetCaptchaAsPasswordResponse }
     * 
     */
    public SetCaptchaAsPasswordResponse createSetCaptchaAsPasswordResponse() {
        return new SetCaptchaAsPasswordResponse();
    }

    /**
     * Create an instance of {@link LoginCert }
     * 
     */
    public LoginCert createLoginCert() {
        return new LoginCert();
    }

    /**
     * Create an instance of {@link GetCert }
     * 
     */
    public GetCert createGetCert() {
        return new GetCert();
    }

    /**
     * Create an instance of {@link GetAttributResponse }
     * 
     */
    public GetAttributResponse createGetAttributResponse() {
        return new GetAttributResponse();
    }

    /**
     * Create an instance of {@link GetNewPassword }
     * 
     */
    public GetNewPassword createGetNewPassword() {
        return new GetNewPassword();
    }

    /**
     * Create an instance of {@link GetDynamicsResponse }
     * 
     */
    public GetDynamicsResponse createGetDynamicsResponse() {
        return new GetDynamicsResponse();
    }

    /**
     * Create an instance of {@link GetNewPasswordResponse }
     * 
     */
    public GetNewPasswordResponse createGetNewPasswordResponse() {
        return new GetNewPasswordResponse();
    }

    /**
     * Create an instance of {@link GetPrivileges }
     * 
     */
    public GetPrivileges createGetPrivileges() {
        return new GetPrivileges();
    }

    /**
     * Create an instance of {@link SetCaptchaAsPassword }
     * 
     */
    public SetCaptchaAsPassword createSetCaptchaAsPassword() {
        return new SetCaptchaAsPassword();
    }

    /**
     * Create an instance of {@link GetSitesResponse }
     * 
     */
    public GetSitesResponse createGetSitesResponse() {
        return new GetSitesResponse();
    }

    /**
     * Create an instance of {@link LoginCertResponse }
     * 
     */
    public LoginCertResponse createLoginCertResponse() {
        return new LoginCertResponse();
    }

    /**
     * Create an instance of {@link IsValidCertResponse }
     * 
     */
    public IsValidCertResponse createIsValidCertResponse() {
        return new IsValidCertResponse();
    }

    /**
     * Create an instance of {@link GetRoles }
     * 
     */
    public GetRoles createGetRoles() {
        return new GetRoles();
    }

    /**
     * Create an instance of {@link SetPasswordCert }
     * 
     */
    public SetPasswordCert createSetPasswordCert() {
        return new SetPasswordCert();
    }

    /**
     * Create an instance of {@link IsNotRevokedCertResponse }
     * 
     */
    public IsNotRevokedCertResponse createIsNotRevokedCertResponse() {
        return new IsNotRevokedCertResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetPassword }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "setPassword")
    public JAXBElement<SetPassword> createSetPassword(SetPassword value) {
        return new JAXBElement<SetPassword>(_SetPassword_QNAME, SetPassword.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDynamics }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getDynamics")
    public JAXBElement<GetDynamics> createGetDynamics(GetDynamics value) {
        return new JAXBElement<GetDynamics>(_GetDynamics_QNAME, GetDynamics.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsAlive }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "isAlive")
    public JAXBElement<IsAlive> createIsAlive(IsAlive value) {
        return new JAXBElement<IsAlive>(_IsAlive_QNAME, IsAlive.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Login }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "login")
    public JAXBElement<Login> createLogin(Login value) {
        return new JAXBElement<Login>(_Login_QNAME, Login.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetNewPassword }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getNewPassword")
    public JAXBElement<GetNewPassword> createGetNewPassword(GetNewPassword value) {
        return new JAXBElement<GetNewPassword>(_GetNewPassword_QNAME, GetNewPassword.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LdapWsException }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "LdapWsException")
    public JAXBElement<LdapWsException> createLdapWsException(LdapWsException value) {
        return new JAXBElement<LdapWsException>(_LdapWsException_QNAME, LdapWsException.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginCryptResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "loginCryptResponse")
    public JAXBElement<LoginCryptResponse> createLoginCryptResponse(LoginCryptResponse value) {
        return new JAXBElement<LoginCryptResponse>(_LoginCryptResponse_QNAME, LoginCryptResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetCaptchaAsPassword }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "setCaptchaAsPassword")
    public JAXBElement<SetCaptchaAsPassword> createSetCaptchaAsPassword(SetCaptchaAsPassword value) {
        return new JAXBElement<SetCaptchaAsPassword>(_SetCaptchaAsPassword_QNAME, SetCaptchaAsPassword.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCertStringAttribut }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getCertStringAttribut")
    public JAXBElement<GetCertStringAttribut> createGetCertStringAttribut(GetCertStringAttribut value) {
        return new JAXBElement<GetCertStringAttribut>(_GetCertStringAttribut_QNAME, GetCertStringAttribut.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginCrypt }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "loginCrypt")
    public JAXBElement<LoginCrypt> createLoginCrypt(LoginCrypt value) {
        return new JAXBElement<LoginCrypt>(_LoginCrypt_QNAME, LoginCrypt.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetCaptchaAsPasswordResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "setCaptchaAsPasswordResponse")
    public JAXBElement<SetCaptchaAsPasswordResponse> createSetCaptchaAsPasswordResponse(SetCaptchaAsPasswordResponse value) {
        return new JAXBElement<SetCaptchaAsPasswordResponse>(_SetCaptchaAsPasswordResponse_QNAME, SetCaptchaAsPasswordResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSitesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getSitesResponse")
    public JAXBElement<GetSitesResponse> createGetSitesResponse(GetSitesResponse value) {
        return new JAXBElement<GetSitesResponse>(_GetSitesResponse_QNAME, GetSitesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProfilResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getProfilResponse")
    public JAXBElement<GetProfilResponse> createGetProfilResponse(GetProfilResponse value) {
        return new JAXBElement<GetProfilResponse>(_GetProfilResponse_QNAME, GetProfilResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCert }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getCert")
    public JAXBElement<GetCert> createGetCert(GetCert value) {
        return new JAXBElement<GetCert>(_GetCert_QNAME, GetCert.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPrivilegesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getPrivilegesResponse")
    public JAXBElement<GetPrivilegesResponse> createGetPrivilegesResponse(GetPrivilegesResponse value) {
        return new JAXBElement<GetPrivilegesResponse>(_GetPrivilegesResponse_QNAME, GetPrivilegesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsNotRevokedCertResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "isNotRevokedCertResponse")
    public JAXBElement<IsNotRevokedCertResponse> createIsNotRevokedCertResponse(IsNotRevokedCertResponse value) {
        return new JAXBElement<IsNotRevokedCertResponse>(_IsNotRevokedCertResponse_QNAME, IsNotRevokedCertResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCertByteAttribut }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getCertByteAttribut")
    public JAXBElement<GetCertByteAttribut> createGetCertByteAttribut(GetCertByteAttribut value) {
        return new JAXBElement<GetCertByteAttribut>(_GetCertByteAttribut_QNAME, GetCertByteAttribut.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetProfil }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getProfil")
    public JAXBElement<GetProfil> createGetProfil(GetProfil value) {
        return new JAXBElement<GetProfil>(_GetProfil_QNAME, GetProfil.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAttribut }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getAttribut")
    public JAXBElement<GetAttribut> createGetAttribut(GetAttribut value) {
        return new JAXBElement<GetAttribut>(_GetAttribut_QNAME, GetAttribut.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetAttributResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getAttributResponse")
    public JAXBElement<GetAttributResponse> createGetAttributResponse(GetAttributResponse value) {
        return new JAXBElement<GetAttributResponse>(_GetAttributResponse_QNAME, GetAttributResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCaptcha }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getCaptcha")
    public JAXBElement<GetCaptcha> createGetCaptcha(GetCaptcha value) {
        return new JAXBElement<GetCaptcha>(_GetCaptcha_QNAME, GetCaptcha.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginCertResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "loginCertResponse")
    public JAXBElement<LoginCertResponse> createLoginCertResponse(LoginCertResponse value) {
        return new JAXBElement<LoginCertResponse>(_LoginCertResponse_QNAME, LoginCertResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetPasswordCert }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "setPasswordCert")
    public JAXBElement<SetPasswordCert> createSetPasswordCert(SetPasswordCert value) {
        return new JAXBElement<SetPasswordCert>(_SetPasswordCert_QNAME, SetPasswordCert.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCertResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getCertResponse")
    public JAXBElement<GetCertResponse> createGetCertResponse(GetCertResponse value) {
        return new JAXBElement<GetCertResponse>(_GetCertResponse_QNAME, GetCertResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCaptchaResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getCaptchaResponse")
    public JAXBElement<GetCaptchaResponse> createGetCaptchaResponse(GetCaptchaResponse value) {
        return new JAXBElement<GetCaptchaResponse>(_GetCaptchaResponse_QNAME, GetCaptchaResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCertStringAttributResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getCertStringAttributResponse")
    public JAXBElement<GetCertStringAttributResponse> createGetCertStringAttributResponse(GetCertStringAttributResponse value) {
        return new JAXBElement<GetCertStringAttributResponse>(_GetCertStringAttributResponse_QNAME, GetCertStringAttributResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetPasswordResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "setPasswordResponse")
    public JAXBElement<SetPasswordResponse> createSetPasswordResponse(SetPasswordResponse value) {
        return new JAXBElement<SetPasswordResponse>(_SetPasswordResponse_QNAME, SetPasswordResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRolesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getRolesResponse")
    public JAXBElement<GetRolesResponse> createGetRolesResponse(GetRolesResponse value) {
        return new JAXBElement<GetRolesResponse>(_GetRolesResponse_QNAME, GetRolesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetNewPasswordResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getNewPasswordResponse")
    public JAXBElement<GetNewPasswordResponse> createGetNewPasswordResponse(GetNewPasswordResponse value) {
        return new JAXBElement<GetNewPasswordResponse>(_GetNewPasswordResponse_QNAME, GetNewPasswordResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsNotRevokedCert }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "isNotRevokedCert")
    public JAXBElement<IsNotRevokedCert> createIsNotRevokedCert(IsNotRevokedCert value) {
        return new JAXBElement<IsNotRevokedCert>(_IsNotRevokedCert_QNAME, IsNotRevokedCert.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginCert }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "loginCert")
    public JAXBElement<LoginCert> createLoginCert(LoginCert value) {
        return new JAXBElement<LoginCert>(_LoginCert_QNAME, LoginCert.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetPrivileges }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getPrivileges")
    public JAXBElement<GetPrivileges> createGetPrivileges(GetPrivileges value) {
        return new JAXBElement<GetPrivileges>(_GetPrivileges_QNAME, GetPrivileges.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRoles }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getRoles")
    public JAXBElement<GetRoles> createGetRoles(GetRoles value) {
        return new JAXBElement<GetRoles>(_GetRoles_QNAME, GetRoles.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCertByteAttributResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getCertByteAttributResponse")
    public JAXBElement<GetCertByteAttributResponse> createGetCertByteAttributResponse(GetCertByteAttributResponse value) {
        return new JAXBElement<GetCertByteAttributResponse>(_GetCertByteAttributResponse_QNAME, GetCertByteAttributResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsValidCert }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "isValidCert")
    public JAXBElement<IsValidCert> createIsValidCert(IsValidCert value) {
        return new JAXBElement<IsValidCert>(_IsValidCert_QNAME, IsValidCert.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetPasswordCertResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "setPasswordCertResponse")
    public JAXBElement<SetPasswordCertResponse> createSetPasswordCertResponse(SetPasswordCertResponse value) {
        return new JAXBElement<SetPasswordCertResponse>(_SetPasswordCertResponse_QNAME, SetPasswordCertResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDynamicsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getDynamicsResponse")
    public JAXBElement<GetDynamicsResponse> createGetDynamicsResponse(GetDynamicsResponse value) {
        return new JAXBElement<GetDynamicsResponse>(_GetDynamicsResponse_QNAME, GetDynamicsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsValidCertResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "isValidCertResponse")
    public JAXBElement<IsValidCertResponse> createIsValidCertResponse(IsValidCertResponse value) {
        return new JAXBElement<IsValidCertResponse>(_IsValidCertResponse_QNAME, IsValidCertResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LoginResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "loginResponse")
    public JAXBElement<LoginResponse> createLoginResponse(LoginResponse value) {
        return new JAXBElement<LoginResponse>(_LoginResponse_QNAME, LoginResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetSites }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "getSites")
    public JAXBElement<GetSites> createGetSites(GetSites value) {
        return new JAXBElement<GetSites>(_GetSites_QNAME, GetSites.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link IsAliveResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ldap.quizzApp.com/", name = "isAliveResponse")
    public JAXBElement<IsAliveResponse> createIsAliveResponse(IsAliveResponse value) {
        return new JAXBElement<IsAliveResponse>(_IsAliveResponse_QNAME, IsAliveResponse.class, null, value);
    }

}
