//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.17 at 04:43:59 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ws.ldap.quizzApp.com/")
package com.adoulfakkar.quizzApp.service.wsdl.auth;
